In [6]:
#Перше завдання 3 номер
import numpy as np
a = np.matrix('1 1 1; 0 1 1; 0 0 1') 
b = np.matrix('7 5 3; 0 7 5; 0 0 7') 
c = a.dot(b) 
print(c)
d = b.dot(a) 
print(d)
g = c - d
print(g) 


[[ 7 12 15]
 [ 0  7 12]
 [ 0  0  7]]
[[ 7 12 15]
 [ 0  7 12]
 [ 0  0  7]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [6]:
#Друге завдання 1 номер
a = np.array([[-1, 2], [0, 1]])
power = np.linalg.matrix_power(a, 2)
print(power)

[[1 0]
 [0 1]]


In [8]:
#Третє завдання 2 номер
a = np.matrix('5 8 -4; 6 9 -5; 4 7 -3')
b = np.matrix('3 2 5; 4 -1 3; 9 6 5')
c = a.dot(b)
print(c)

[[ 11 -22  29]
 [  9 -27  32]
 [ 13 -17  26]]


In [18]:
#Четверте завдання 1 номер
a = np.matrix('2 3 4; 1 0 6; 7 8 9')
print(a)
np.linalg.det(a)

[[2 3 4]
 [1 0 6]
 [7 8 9]]


35.00000000000001

In [10]:
#П'яте завдання 2 номер
a = np.matrix('2 3 4 1; 1 2 3 4; 3 4 1 2; 4 1 2 3')
print(a)
np.linalg.det(a)

[[2 3 4 1]
 [1 2 3 4]
 [3 4 1 2]
 [4 1 2 3]]


-160.00000000000009

In [11]:
#Шосте завдання 3 номер
a = np.matrix('1 2 2; 2 1 -2; 2 -2 1')
a_inv = np.linalg.inv(a)
print(a_inv)

[[ 0.11111111  0.22222222  0.22222222]
 [ 0.22222222  0.11111111 -0.22222222]
 [ 0.22222222 -0.22222222  0.11111111]]


In [12]:
#Сьоме завдання 3 номер
a = np.matrix('-2 3 1 -1; 3 2 1 4; 1 2 3 4; 0 2 3 3')
rank = np.linalg.matrix_rank(a)
print(rank)

3


In [7]:
#Восьме завдання 11 номер. Матричний метод
a = np.matrix('2 -1 1; 3 4 -2; 1 -3 1')
b = np.matrix('5; -3; 4')
print('A=', a)
print('B=',b)
a_inv = np.linalg.inv(a)
print(a_inv)
x = a_inv.dot(b)
print('X=',x)

A= [[ 2 -1  1]
 [ 3  4 -2]
 [ 1 -3  1]]
B= [[ 5]
 [-3]
 [ 4]]
[[ 0.16666667  0.16666667  0.16666667]
 [ 0.41666667 -0.08333333 -0.58333333]
 [ 1.08333333 -0.41666667 -0.91666667]]
X= [[ 1.0000000e+00]
 [-4.4408921e-16]
 [ 3.0000000e+00]]


In [9]:
#Восьме завдання 11 номер. Метод Крамера
a = np.matrix('2 -1 1; 3 4 -2; 1 -3 1')
print('A=',a)
b = np.matrix('5; -3; 4')
print('B=',b)

def kramer (a, b):
    a_det = np.linalg.det(a)
    print('Детермінант матриці = ', a_det)
#Зробити реревірку,що детермінант не дорівнює нулю
    if (a_det != 0):
        print ('Розв*язуємо систему')
        
        x_m = np.matrix(a)
        x_m[:, 0] = b # 1 cт. замінюємо на  ст.b
        print('x_m=', x_m)
        y_m = np.matrix(a)
        y_m[:, 1] = b # 2 cт. замінюємо на  ст.b
        print('y_m=',y_m)

        z_m = np.matrix(a)
        z_m[:, 2] = b # 3 cт. замінюємо на  ст.b
        print('z_m=',z_m)

        x = np.linalg.det(x_m) / a_det
        y = np.linalg.det(y_m) / a_det
        z = np.linalg.det(z_m) / a_det
        print('X = ', round(x,5))
        print('Y=', round(y,5))
        print('Z=', round(z,5))
    else:
        print('Розв*язків немає')
kramer(a,b)

A= [[ 2 -1  1]
 [ 3  4 -2]
 [ 1 -3  1]]
B= [[ 5]
 [-3]
 [ 4]]
Детермінант матриці =  -12.0
Розв*язуємо систему
x_m= [[ 5 -1  1]
 [-3  4 -2]
 [ 4 -3  1]]
y_m= [[ 2  5  1]
 [ 3 -3 -2]
 [ 1  4  1]]
z_m= [[ 2 -1  5]
 [ 3  4 -3]
 [ 1 -3  4]]
X =  1.0
Y= 0.0
Z= 3.0


In [30]:
#Останнє завдання номер 5
a = np.array([[0, 2, 1], [0, 1, 2], [1, 2, 3]])
print(a)
suma = np.sum(a)
print("Сума всіх елемнтів =", suma)
suma1 = np.sum(a[0])
print("Сума елемнтів 1 рядка =",suma1)
suma2 = np.sum(a[1])
print("Сума елементів 2 рядка =",suma2)
suma3 = np.sum(a[2])
print("Сума елементів 3 рядка =",suma3)
portion1 = suma1 / suma * 100
portion2 = suma2 / suma * 100
portion3 = suma3 / suma * 100
print("Доля 1 рядка =", portion1,"%")
print("Доля 2 рядка =", portion2,"%")
print("Доля 3 рядка =", portion3,"%")

[[0 2 1]
 [0 1 2]
 [1 2 3]]
Сума всіх елемнтів = 12
Сума елемнтів 1 рядка = 3
Сума елементів 2 рядка = 3
Сума елементів 3 рядка = 6
Доля 1 рядка = 25.0 %
Доля 2 рядка = 25.0 %
Доля 3 рядка = 50.0 %
